import "./globals.css";
import NextAuthProvider from "./providers";
import ReduxProvider from "@/lib/redux/Provider";

import ThemeProvider from "@/app/ThemeProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ReduxProvider>
          <NextAuthProvider>
            <ThemeProvider>
              <div className="bg-skin-fill text-base">
                <div className="container mx-auto">
                  <Navbar />
                  <main className="px-3">{children}</main>
                  <Footer />
                </div>
              </div>
            </ThemeProvider>
          </NextAuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
