import './globals.css'
import NextAuthProvider from "./providers";
import ReduxProvider from "@/lib/redux/Provider";

// import { Inter } from 'next/font/google'
import ThemeProvider from '@/app/ThemeProvider'
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ReduxProvider>
          <NextAuthProvider>
            <div className='bg-bg-l dark:bg-bg-d text-textp-l dark:text-textp-d'>
              <ThemeProvider>
                <div className='container mx-auto'>
                  <Navbar />
                  <main>{children}</main>
                  <Footer />
                </div>
              </ThemeProvider>
            </div>
          </NextAuthProvider>
        </ReduxProvider>
      </body>
    </html>
  )
}
